version: "3.8"
services:
  postgres:
    container_name: jobscontrol
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jobscontrol
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/jobscontrol
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: admin
    depends_on:
      - postgres
