version: '3.8'
services:
  postgres:
    container_name: jobscontrol
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jobscontrol